### ISSUE TITLE
Working with webpack

### ISSUE THREAD

**Issue by cloudy064** [archiverjs/node-archiver#174]
When I developed my app with node-archiver, I found it can't work well with webpack, reporting an error as follows:
```
[1264:1229/111321:ERROR:nw_shell.cc(336)] Error: append: input source must be valid Stream or Buffer instance
    at Archiver.append (file:///Users/cloudy/workspaces/javascript/push_message/bundle.js:22004:25)
    at Object.<anonymous> (file:///Users/cloudy/workspaces/javascript/push_message/bundle.js:963:10)
    at __webpack_require__ (file:///Users/cloudy/workspaces/javascript/push_message/bundle.js:20:30)
    at Object.<anonymous> (file:///Users/cloudy/workspaces/javascript/push_message/bundle.js:47:19)
    at __webpack_require__ (file:///Users/cloudy/workspaces/javascript/push_message/bundle.js:20:30)
    at file:///Users/cloudy/workspaces/javascript/push_message/bundle.js:40:18
    at file:///Users/cloudy/workspaces/javascript/push_message/bundle.js:43:10
```
However, it works well when running demo separately.

**Comment by VikramTiwari** [comment]
Hey, @cloudy064 Did you ever find a solution to this?
