### ISSUE TITLE
Does not work in node v6

### ISSUE THREAD

**Issue by dickeyxxx** [archiverjs/node-archiver#187]
```
npm test

> archiver@1.0.0 test /Users/jdickey/src/github.com/archiverjs/node-archiver
> mocha --reporter dot



  ․․․․․․․․․․․․․․․․

  10 passing (93ms)
  6 failing

  1) archiver api #append "before all" hook:
     Uncaught Error: If encoding is specified then the first argument must be a string
      at new Buffer (buffer.js:106:13)
      at ReadStream.<anonymous> (node_modules/archiver-utils/index.js:39:15)
      at endReadableNT (_stream_readable.js:926:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

  2) archiver api #directory "before all" hook:
     Uncaught Error: If encoding is specified then the first argument must be a string
      at new Buffer (buffer.js:106:13)
      at Readable.<anonymous> (node_modules/archiver-utils/index.js:39:15)
      at endReadableNT (_stream_readable.js:926:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

  3) archiver api #file "before all" hook:
     Uncaught Error: If encoding is specified then the first argument must be a string
      at new Buffer (buffer.js:106:13)
      at Readable.<anonymous> (node_modules/archiver-utils/index.js:39:15)
      at endReadableNT (_stream_readable.js:926:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

  4) archiver api #bulk "before all" hook:
     Uncaught Error: If encoding is specified then the first argument must be a string
      at new Buffer (buffer.js:106:13)
      at Readable.<anonymous> (node_modules/archiver-utils/index.js:39:15)
      at endReadableNT (_stream_readable.js:926:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

  5) archiver api #glob "before all" hook:
     Uncaught Error: If encoding is specified then the first argument must be a string
      at new Buffer (buffer.js:106:13)
      at Readable.<anonymous> (node_modules/archiver-utils/index.js:39:15)
      at endReadableNT (_stream_readable.js:926:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

  6) plugins tar "before all" hook:
     Uncaught Error: If encoding is specified then the first argument must be a string
      at new Buffer (buffer.js:106:13)
      at ReadStream.<anonymous> (node_modules/archiver-utils/index.js:39:15)
      at endReadableNT (_stream_readable.js:926:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)



npm ERR! Test failed.  See above for more details.
```

**Comment by ctalkington** [comment]
This should be fixed via archiverjs/archiver-utils v1.2.0. Due to new version using ^ versioning it should be automatic without a need for an archiver release.
