### ISSUE TITLE
Error out on multiple zippings

### ISSUE THREAD

**Issue by ruwang** [archiverjs/node-archiver#193]
Everything goes fine when I have single zipping instance, however, when there are multiple zipping instances. The zipping process fails.

Example codes:
```
'use strict';

const path = require('path');
const fs = require('fs');
const archiver = require('archiver');
const archive = new archiver('zip', {});

const zip = (opts) => {
  const filePath = opts.fileName;
  // Zip files for tus client upload
  const zipFile = `${path.basename(filePath)}.zip`;
  const output = fs.createWriteStream(zipFile);
  output.on('close', () => {
    console.log(`${zipFile} created`);
  });
  archive.on('error', (err) => {
    throw new Error('Error during zipping files:', err);
  });
  archive.pipe(output);
  archive.file(filePath, { name: path.basename(filePath) });
  archive.finalize();
};

zip({ fileName: 't.js' });
zip({ fileName: 't2.js' });
```
Error:

```
Error: Error during zipping files:
    at null.<anonymous> (/coins/penny-collector/ziptest.js:17:11)
    at emitOne (events.js:82:20)
    at emit (events.js:169:7)
    at Archiver.file (/coins/penny-collector/node_modules/archiver/lib/core.js:689:10)
    at archive.on (/coins/penny-collector/ziptest.js:20:11)
    at Object.<anonymous> (/coins/penny-collector/ziptest.js:26:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

Any fix? Thanks.

**Comment by ruwang** [comment]
I realized that two zips are on the same archive instance that causes the issue. moving the instantiation inside the function fixes the issue.
