### ISSUE TITLE
ReferenceError: entryData is not defined

### ISSUE THREAD

**Issue by arichiardi** [archiverjs/node-archiver#272]
Hello folks!

I think I found a little bug in the `glob` patterns, and I am not sure why the tests are not catching it.

In any case, [this](https://github.com/archiverjs/node-archiver/blob/master/lib/core.js#L722) is the location of the bug. Is it just a matter of creating a `var`?

I can contribute that if so.

Thanks!

Full error:

```
entryData = _.extend({}, data);
              ^

ReferenceError: entryData is not defined
    at Archiver.onGlobMatch (/home/arichiardi/git/serverless-cljs-plugin/node_modules/archiver/lib/core.js:715:15)
    at emitOne (events.js:115:13)
    at Glob.emit (events.js:210:7)
    at Glob._emitMatch (/home/arichiardi/git/serverless-cljs-plugin/node_modules/glob/glob.js:489:8)
    at Glob._processSimple2 (/home/arichiardi/git/serverless-cljs-plugin/node_modules/glob/glob.js:705:8)
    at /home/arichiardi/git/serverless-cljs-plugin/node_modules/glob/glob.js:676:10
    at Glob._stat (/home/arichiardi/git/serverless-cljs-plugin/node_modules/glob/glob.js:725:14)
    at Glob._processSimple (/home/arichiardi/git/serverless-cljs-plugin/node_modules/glob/glob.js:675:8)
    at Glob._process (/home/arichiardi/git/serverless-cljs-plugin/node_modules/glob/glob.js:325:12)
    at Glob._processGlobStar2 (/home/arichiardi/git/serverless-cljs-plugin/node_modules/glob/glob.js:646:8)
```

**Comment by ctalkington** [comment]
odd, i know there has been some discussion on using const vs var but it must gotten removed at some point and maybe you are in stict mode or something.
