### ISSUE TITLE
TypeError: pna.nextTick is not a function

### ISSUE THREAD

**Issue by alexisohayon** [archiverjs/node-archiver#315]
Hello,

I'm facing an issue for the last days that I can't manage to solve :/
Everything is working well on my dev environment (mac os), but when I try to use it on my prod environment, which runs under docker, the declaration of:
```
      let archive = archiver('zip');
```
causes me this error of "pna.nextTick is not a function"...

I tried so many different things, nothing seems to fix this issue...
Did anyone already face it?

Thanks a lot!

**Comment by alexisohayon** [comment]
The full error stack:
```
backend_1  |     TypeError: pna.nextTick is not a function
backend_1  |     at resume (/src/app/node_modules/compress-commons/node_modules/readable-stream/lib/_stream_readable.js:783:9)
backend_1  |     at module.exports.Readable.resume (/src/app/node_modules/compress-commons/node_modules/readable-stream/lib/_stream_readable.js:775:5)
backend_1  |     at module.exports.Readable.on (/src/app/node_modules/compress-commons/node_modules/readable-stream/lib/_stream_readable.js:745:53)
backend_1  |     at module.exports.Readable.pipe (/src/app/node_modules/compress-commons/node_modules/readable-stream/lib/_stream_readable.js:615:7)
backend_1  |     at Zip.pipe (/src/app/node_modules/archiver/lib/plugins/zip.js:75:27)
backend_1  |     at Archiver._modulePipe (/src/app/node_modules/archiver/lib/core.js:250:16)
backend_1  |     at Archiver.setModule (/src/app/node_modules/archiver/lib/core.js:832:8)
backend_1  |     at Function.vending.create (/src/app/node_modules/archiver/index.js:35:14)
backend_1  |     at vending (/src/app/node_modules/archiver/index.js:21:18)
backend_1  |     at Promise (/src/app/api/internal/util/invoices.js:78:21)
backend_1  |     at <anonymous>
```

**Comment by alexisohayon** [comment]
As I'm using the official node docker image (9.3.0), this is not the origin of the problem but I solved it by installing readable-stream myself, forcing it to be updated... If anyone face this problem again :)
