### ISSUE TITLE
processNextTick is not a function

### ISSUE THREAD

**Issue by JustinDFuller** [archiverjs/node-archiver#330]
Module Version: "^2.1.1"
Node version: v8.9.4

Here's the error I'm receiving:

"message":"processNextTick is not a function",
  "name":"TypeError",
  "stack":"TypeError: processNextTick is not a function\n    at resume (/hosting/my-application/node_modules/readable-stream/lib/_stream_readable.js:703:5)\n    at module.exports.Readable.resume (/hosting/my-application/node_modules/readable-stream/lib/_stream_readable.js:695:5)\n    at module.exports.Readable.on (/hosting/my-application/node_modules/readable-stream/lib/_stream_readable.js:665:53)\n    at module.exports.Readable.pipe (/hosting/my-application/node_modules/readable-stream/lib/_stream_readable.js:536:7)\n    at Zip.pipe (/hosting/my-application/node_modules/archiver/lib/plugins/zip.js:75:27)\n    at Archiver._modulePipe (/hosting/my-application/node_modules/archiver/lib/core.js:250:16)\n    at Archiver.setModule (/hosting/my-application/node_modules/archiver/lib/core.js:832:8)\n    at Function.vending.create (/hosting/my-application/node_modules/archiver/index.js:35:14)\n    at vending (/hosting/my-application/node_modules/archiver/index.js:21:18)\n    at /hosting/my-application/src/api/controllers/artifacts.js:185:21\n"

Code I'm using:

```js
const archive = archiver('zip'); // error happens here (line 185 in stack trace above)
const { type = 'build', targetId = 0 } = query;

response.set({
    'Content-Type': 'application/octet-stream',
    'Content-disposition': `attachment; filename=${type}_${targetId}.zip`,
});

archive.pipe(response, { end: false });
```

Relevant dependencies.. readable-stream@2.3.6

**Comment by JustinDFuller** [comment]
Specifying the dep "readable-stream": "2.3.4" fixes the issue
