### ISSUE TITLE
[SOLVED] not a function

### ISSUE THREAD

**Issue by tbhaxor** [archiverjs/node-archiver#379]
When i tried run the script, it exited with this method

```
/home/terabyte/Programs/4IR/akira-intergrity/bin/linux/dist/backup.js:56
      var zipper = archiver("zip", {
                   ^

TypeError: archiver is not a function
    at Backup._do (/home/terabyte/Programs/4IR/akira-intergrity/bin/linux/dist/backup.js:56:20)
    at Object.<anonymous> (/home/terabyte/Programs/4IR/akira-intergrity/bin/linux/dist/app.js:67:13)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at Object.<anonymous> (/home/terabyte/Programs/4IR/akira-intergrity/bin/linux/akira:349:30)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
```

and here is the code of the function

```js
    /**
     * @function zip
     * @description Method to zip the directory
     * @param {string} dir
     * @memberof Zipper
     * @returns {Promise}
     */
    do(dir) {
        let id = randomStr();
        let fileName = id + ".zip";
        let dest = path.join(backupDir, fileName);
        let output = fs.createWriteStream(dest);
        let zipper = archiver("zip", { comment: "Backup for " + dir, zlib: 9 });
        output.pipe(zipper);
        output.on("close", function() {
            console.log(zipper.pointer() + " total bytes");
            console.log(
                "archiver has been finalized and the output file descriptor has closed."
            );
        });
        output.on("end", function() {
            console.log("Data has been drained");
        });
        zipper.directory(dir);
        zipper.finalize();
    }
```

**Comment by ngarg-panw** [comment]
Hi, I am facing the same issue.How did you solve it?
