### ISSUE TITLE
as soon as I require archiver I see a syntax error

### ISSUE THREAD

**Issue by jaydave1412** [archiverjs/node-archiver#447]
```
C:\xampp\htdocs\archiver_demo\node_modules\readdir-glob\index.js:62
async function* exploreWalkAsync(dir, path, followSyslinks, useStat, strict) {
              ^

SyntaxError: Unexpected token *  
    at createScript (vm.js:80:10)    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\xampp\htdocs\archiver_demo\node_modules\archiver\lib\core.js:9:12)
```

My code 

```
const express = require('express');
const app = express();
const fs = require('fs');
const archiver = require('archiver');


app.use(express.static('public'));
app.get('/archive',(req,res)=>{

res.download(__dirname+'/archiver/temp.csv')
})


app.listen(4000,()=>{
    console.log("listening to 4000");
})
```

**Comment by ctalkington** [comment]
what version of node?

**Comment by jaydave1412** [comment]
8.11.3

**Comment by ctalkington** [comment]
you will need to use an older version of archiver as v5 only supports 10+
