### ISSUE TITLE
Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by maifeeulasad** [archiverjs/node-archiver#711]
I get this error on import with `archiver`
Stack-trace:
```
Uncaught TypeError: Class extends value undefined is not a constructor or null
    at node_modules/readdir-glob/index.js (index.js:120:1)
    at __require (chunk-J43GMYXM.js?v=5acb6c3b:11:50)
    at node_modules/archiver/lib/core.js (core.js:9:12)
    at __require (chunk-J43GMYXM.js?v=5acb6c3b:11:50)
    at node_modules/archiver/index.js (index.js:8:16)
    at __require (chunk-J43GMYXM.js?v=5acb6c3b:11:50)
    at node_modules/to-spreadsheet/lib/generate-excel.js (generate-excel.js:16:18)
    at __require (chunk-J43GMYXM.js?v=5acb6c3b:11:50)
    at node_modules/to-spreadsheet/lib/index.js (index.js:4:26)
    at __require (chunk-J43GMYXM.js?v=5acb6c3b:11:50)
```
This works fine on CLI based node project. But when I try to call `generateExcel` method from `to-spreadsheet` I get this error. This library is using `archiver` under the hood.

How can I resolve this issue?

**Comment by Nitroxone** [comment]
Hi,

Same error here, on a Nuxt3 project while trying to simply import archiver in a component.
Tried both :
`import { archiver } as 'archiver'`
and
`import * as archiver from 'archiver'` 

But none seem to work.

**Comment by Uzair16ahmed** [comment]
@maifeeulasad @savisra any solutions or workaround regarding this?

**Comment by maifeeulasad** [comment]
`archiver` only works in node environment, to have similar functionality you can try `jszip` and `file-saver`.

Feel free to explore the related code here: https://github.com/maifeeulasad/to-spreadsheet/blob/5b11d3eadbde2ed69fe64b9f07872e38e5f963f3/src/generate-excel.ts#L78-L147

I am simply checking the environment first them doing conditional import and then performing operations.

Sorry for the late reply! Good day!
